// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategoria(arg1:models.Categoria):Promise<number>;

export function DeleteCategoria(arg1:number):Promise<void>;

export function ListarCategorias():Promise<Array<models.Categoria>>;

export function UpdateCategoria(arg1:models.Categoria):Promise<void>;
