// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategoria(arg1) {
  return window['go']['bindings']['CategoriaBindings']['CreateCategoria'](arg1);
}

export function DeleteCategoria(arg1) {
  return window['go']['bindings']['CategoriaBindings']['DeleteCategoria'](arg1);
}

export function ListarCategorias() {
  return window['go']['bindings']['CategoriaBindings']['ListarCategorias']();
}

export function UpdateCategoria(arg1) {
  return window['go']['bindings']['CategoriaBindings']['UpdateCategoria'](arg1);
}
