// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEstoque(arg1) {
  return window['go']['bindings']['EstoqueBindings']['CreateEstoque'](arg1);
}

export function GetAllEstoques() {
  return window['go']['bindings']['EstoqueBindings']['GetAllEstoques']();
}

export function UpdateEstoque(arg1) {
  return window['go']['bindings']['EstoqueBindings']['UpdateEstoque'](arg1);
}
