// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEstoque(arg1:models.Estoque):Promise<number>;

export function GetAllEstoques():Promise<Array<models.Estoque>>;

export function UpdateEstoque(arg1:models.Estoque):Promise<void>;
