// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduto(arg1) {
  return window['go']['bindings']['ProdutoBindings']['CreateProduto'](arg1);
}

export function DeleteProduto(arg1) {
  return window['go']['bindings']['ProdutoBindings']['DeleteProduto'](arg1);
}

export function GetProduto(arg1) {
  return window['go']['bindings']['ProdutoBindings']['GetProduto'](arg1);
}

export function ListAllProdutos() {
  return window['go']['bindings']['ProdutoBindings']['ListAllProdutos']();
}

export function UpdateProduto(arg1) {
  return window['go']['bindings']['ProdutoBindings']['UpdateProduto'](arg1);
}
