// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateProduto(arg1:models.Produto):Promise<number>;

export function DeleteProduto(arg1:number):Promise<void>;

export function GetProduto(arg1:number):Promise<models.Produto>;

export function ListAllProdutos():Promise<Array<models.Produto>>;

export function UpdateProduto(arg1:models.Produto):Promise<void>;
